---
layout: post
title: 再看Delphi的异常处理
categories: delphi之异常处理 
tags: delphi 异常处理
---

需要参考之前我整理的关于Delphi的异常处理的文章

* [Delphi异常处理时代码的执行逻辑](http://www.xumenger.com/delphi-exception-20151201/)
* [Delphi中的异常处理](http://www.xumenger.com/delphi-exception-20150428/)
* [Delphi中的异常处理](http://www.xumenger.com/delphi-exception/)

## try..except和try..finally的一般使用顺序

因为在Delphi中没有try..except..finally..end的异常处理语法，所以下面代码中这种try..except和try..finally结合使用的方式比较常见

其运行时候的逻辑是这样的：

* 在抛出异常后，和异常在同一个逻辑层次的ShowMessage('after exception');不会被执行
* 因为会在except中捕获异常，所以这里面的代码会被执行
* finally里面的代码是无论如何都要执行的，所以接下来会运行到finally里面的代码中
* 注意直接双击编译后的exe文件和通过在Delphi中调试的运行效果会不一样
	* 上面所描述的是直接双击编译得到的exe文件的运行效果
	* 如果通过在Delphi的IDE中调试的形式，可能会在抛出异常的地方多弹出一次框
	* 在下面的代码也是这样的

```
unit Unit1;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls;

type
  TForm1 = class(TForm)
    btn1: TButton;
    procedure btn1Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.dfm}

procedure TForm1.btn1Click(Sender: TObject);
begin
  try
    try
      raise Exception.Create('exception');
      ShowMessage('after exception');
    except
      on E: Exception do
      begin
        ShowMessage(E.Message);
      end;
    end
  finally
    ShowMessage('finally');
  end;
end;

end.
```

## try..except和try..finally的一种不常见的使用顺序

下面代码中的这种异常处理逻辑要小心

* 在抛出异常后，和异常在同一个逻辑层次的ShowMessage('after exception');不会被执行
* 会跳到finally里面
* 但是不要以为从在finally里面执行完之后就结束了，以前我就是这么错误认为的
* 因为它抛出的异常并没有被捕获，所以会继续往外抛异常
* 所以下面的except的逻辑可以捕获异常，所以就会继续执行

```
unit Unit1;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls;

type
  TForm1 = class(TForm)
    btn1: TButton;
    procedure btn1Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.dfm}

procedure TForm1.btn1Click(Sender: TObject);
begin
  try
    try
      raise Exception.Create('exception');
      ShowMessage('after exception');
    finally
      ShowMessage('finally');
    end;
  except
    on E: Exception do
    begin
      ShowMessage(E.Message)
    end;
  end;
end;

end.
 ```
